services:
  jqplay:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jqplay
    environment:
      NODE_ENV: development
    command: npm run dev
    ports:
      - "3067:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
