# syntax = docker/dockerfile:1

FROM node:25

WORKDIR /app

COPY package*.json ./
COPY prisma/ ./prisma/
COPY scripts/ ./scripts/

RUN npm install

COPY . .

# Expose the development server port
EXPOSE 3000

# Set default command
CMD ["npm", "run", "dev"]
